---
  # root already extends zillow-base
  rules:
    # match upstream because dangling comma conflicts are _the worst_
    comma-dangle: off
    # ditto for indent
    indent: [error, 2]
    # far too many disagreements to be useful
    prettier/prettier: off
