---
  root: true
  extends:
    - zillow-base
    - plugin:jest/recommended
  plugins:
    - jest
  env:
    jest/globals: false
  rules:
    strict: "off"
  overrides:
    - files: "**/test/**"
      env:
        jest/globals: true
    - files: "packages/zillow-browser-shims/document-contains.js"
      rules:
        func-name-matching: "off"
    - files: "packages/babel-preset-zillow/index.js"
      rules:
        prefer-object-spread: "off"
