---
  root: true
  extends:
    - zillow-base
    - plugin:jest/recommended
  plugins:
    - jest
  env:
    jest/globals: false
  rules:
    prefer-destructuring: off
    strict: off
  overrides:
    - files: "**/test/**"
      env:
        jest/globals: true
