# don't build tags, it's redundant
if: tag IS blank
language: node_js
node_js:
  - "10"
  - "8"
cache:
  directories:
  - $HOME/.npm
before_install:
  - nvm install-latest-npm
install:
  - npm ci
  - if [ "${ESLINT}" -eq "4" ]; then npm install --no-save "eslint@${ESLINT}"; fi
script:
  - npm t
sudo: false
env:
  global:
    - NO_UPDATE_NOTIFIER=1
  matrix:
    - ESLINT=5
    - ESLINT=4
matrix:
  fast_finish: true
